### ISSUE TITLE
Function to show all foods in the database needed

### ISSUE THREAD

**Issue by GiammarcoBozzelli** [GiammarcoBozzelli/FoodLover#5]
There is the need for a function showing to the users all available foods in the CSV file.

**Comment by HabibAngelica** [comment]
Is it a good idea to show them by their initial letter? 'ShowFood' (inside 'Choice' branch) is the function for the selection. Do we have any input function to help the user selecting the letter?

**Comment by GiammarcoBozzelli** [comment]
No, I think it is better to have inside the show function itself the input section for the letter
@HabibAngelica
