### ISSUE TITLE
Delete the branch or not

### ISSUE THREAD

**Issue by HabibAngelica** [GiammarcoBozzelli/FoodLover#6]
Hi everyone, this branch was done because we had in mind other functions. now the path has changed, do we want to delete it or to keep it just for some final tests?

**Comment by GiammarcoBozzelli** [comment]
Since we did not use it and it was only a test, I think we can delete it
What do you think? @Etta01 @ErosLovato885006

**Comment by ErosLovato885006** [comment]
I totally agree

**Comment by Etta01** [comment]
yes I agree too!

**Comment by HabibAngelica** [comment]
ok guys
