### ISSUE TITLE
Fix update.py inputs

### ISSUE THREAD

**Issue by GiammarcoBozzelli** [GiammarcoBozzelli/FoodLover#7]
Hi  @ErosLovato885006 I tried launching update.py and saw that the inputs are checked all at the end and not one at the time, I think we should check them one at the time and maybe add a while loop at the beginning, such that if the user inputs a wrong value he/she doesn't have to start all over

**Comment by ErosLovato885006** [comment]
thanks Giammarco for the notice, I've just finished working on it tell me if now it's okay

**Comment by GiammarcoBozzelli** [comment]
> thanks Giammarco for the notice, I've just finished working on it tell me if now it's okay

The inputs are perfect, but there is an issue when you write the new line into the dataset, the input values are in the wrong columns 
@ErosLovato885006

**Comment by ErosLovato885006** [comment]
thanks for letting me know @GiammarcoBozzelli , I'm working on it
