### ISSUE TITLE
Adjust CleanDataProva.py to handle input 

### ISSUE THREAD

**Issue by GiammarcoBozzelli** [GiammarcoBozzelli/FoodLover#8]
Hi @HabibAngelica I was testing your function get_info() and noticed that the input given to the function need to be adjusted. The function receives as input all arguments collected at the beginning, meaning we need to extract each time the single values from there, You can also add the update_dataframe() function under the 'if add == True' since Eros did it!

**Comment by HabibAngelica** [comment]
Thank you @GiammarcoBozzelli for the valid observation. Check it now
